server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://wlsdnr4675.cwjff3qij1v0.ap-northeast-2.rds.amazonaws.com/wlsdnr4675?useSSLd=false&characterEncoding=UTF-8&serverTimezone=UTC
    # username: wlsdnr4675
    # password: wlsdnr4675
    url: jdbc:mysql://192.168.0.17:3306/arte?useSSLd=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: arte
    password: Arte1234
    # url: jdbc:mysql://localhost/team_project?useSSLd=false&characterEncoding=UTF-8&serverTimezone=UTC
    # username: root
    # password: dkdlxl123
    servlet:
      multipart:
        enabled: true
        location: Users/jinwookoh/Desktop/ResumeFile/
        max-request-size: 30MB
        max-file-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: secret-value
shop:
  jinwookoh:
    upload:
      path: /Users/jinwookoh/Desktop/ResumeFile/

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
